# Generated by Django 5.1.6 on 2025-02-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
# This is what our jobs dataset currently looks like
    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
