# Generated by Django 5.1.6 on 2025-03-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_location_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='slug',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='Location Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default='Salary Unknown', max_length=50),
        ),
    ]
