# Generated by Django 5.1.6 on 2025-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobs_slug_alter_jobs_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='url',
            field=models.URLField(default='Kumoscraper.tech', unique=True),
        ),
    ]
